@startuml
skinparam rectangle {
  BackgroundColor<<sensor>> LightBlue
  BackgroundColor<<actuator>> LightGreen
  BackgroundColor<<comm>> LightYellow
}

rectangle "Microcontrolador" as mc
rectangle "LoRa" as lora <<comm>>
rectangle "GPS" as gps <<sensor>>
rectangle "IMU" as imu <<sensor>>
rectangle "PWM" as pwm
rectangle "Motor 1" as M1 <<actuator>>
rectangle "Motor N" as Mn <<actuator>>

' MC ligado ao bus
mc -- gps
mc -- imu
mc -- pwm
mc -- lora
gps -[dashed]right- imu
lora -right[hidden]- gps

' Motores ligados ao PWM
pwm -down-> M1
M1 -[dashed]right- Mn
pwm -down-> Mn

' Utilizador via LoRa
actor usr as "User"
lora <-[dashed]-> usr : LoRa
@enduml
